[package]
name = "procmacros"

version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
reqwest = { version = "0.12.5", features = ["blocking"] }
serde_json = "1.0.122"
syn = "2.0.72"

[lib]
proc-macro = true
